language: node_js
node_js:
- '6'
script:
- set -e
- npm run test
- npm run coveralls
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- npm config set git-tag-version=false
- NPM_VERSION=$(npm version patch)
- git commit -a -m "${NPM_VERSION:1}" -m "[ci skip]"
- git remote remove origin
- git remote add origin https://${GITHUB_TOKEN}@github.com/xpl/string.bullet.git
- git push origin HEAD:master
deploy:
  provider: npm
  email: rocket.mind@gmail.com
  api_key:
    secure: c42kk4Kr5aZFzpssPT99Ey8jhmK8LYWutuGGqYNP7jGnjqN7xkvf/j5BPcjNzCeU8qWyuXP9YqqR7rCVEE6MWNheit8ybhJ9GgCTnCyacCUPprD7uu4vwD6C2JFSITkvKpuH5XnPHML4cdpfHySyPDeHfLQP1ldOsNHTN+EY8Wn7mL0MDUYjx7Ree0q6FlV8oaJ8zP8A7dRaE5VMjwKkidAguSvCdmkwMYsXWAOze43SDQ6AgFi9VrMeUwsCKkvoEsLmz6Fq8/nffFnZQhRJPZOMWdQjMFDM0GiqbYcpbZdlFupp9ySc7u1r2In9T09824R8X0FGNIgcmIjlztY4dH09q5ox/trouUsK1u/VHDv0p/peJcSJlNS6AvI28zFhLaimOz4LUSS4NJ3Z/GhjwofImRT3U1VjUBR8pAtF3aYfKLl4cBAYb9anVgmvuM48u+Ve4FYVhnaonwSxlwNvvg4w8rGOaj0Qqjd7sNF7NaLJ7cU1RC7yqShi3mHHLartj6h1Fie/FuQd7z7MifAYWUPEh2SMUX5tFgSPF/MUQKWEn+8rlA4Ki5J1i9BY4KSLkOsezA3/8FAJrgcKeLesbPpme9P8g/XEHAOmAUyvKtFhoyypSzQtcCRmKdrSBjKOsi7tAMo+sLczAHpJHexxhNpTtiAMV9dGyPiGp4Ooz2M=
env:
  global:
  - secure: VKnG8iq4D4Bgen3d6fNr9AXcofzcygtgCHcrY0X3uECHlYr3BXF0HYs47/uTQoz9060Rwz5HipaTcFhXgnhd7X/yoI+/ObrGd0MDQu/jd5vpVmEi7JoZwXF+Te1/VmfsTJSrGM9mtteeYAb60x0MeiX+k0a8K8E/3mbPIwoHYCKkEezV/C25BUrW3Urwlo9qJBrpdWxG1aQPamyT80VoVH9F0zqA1AjQiBI1bmAPSOMfniLAqceqvuFNLJl/sZvWtMsaGu00DXT0+kniySvw133FcICscgw12xcwcdWW2oGm7527g/hw+y8FiIu1Js7Sq0IyMgGIh8ZONZSKhPNr+VZeIQhzMwGi0j+H1+Nf1AAhlTgihCllkfJGb93dT0FTlLiUJOuzAG7O5RIGcD5l5Z2MjheNPaoxbyeLA0blPlrXQBvKCDMq9jlONZN4ysUY72r+9nLmwZlshnVLkG1KIiBYr5su1eO9sUiPSQnVj34opuyd/E/cG35W4A3w6da+h5FR79LFI+X6Mi1jfvIjpte0ba4D+fd+U0i9WARP1k/u6eJq435b0tEkU5vs8RFAjgDe62P60Dngyc2FeFe1ezFst24wNziqhoMOuf1LeylPnaiGfI9Xo4lD3UFwBFEAb6sPZ5V6liRQWLrrLurtz5hCpXvLL4ABnAJ4nj53DKc=
